# Generated by Django 4.2.13 on 2024-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sat', models.IntegerField()),
                ('act', models.IntegerField()),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
