# Generated by Django 4.2.13 on 2024-05-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collegestats',
            table='CollegeStats',
        ),
    ]
