# Generated by Django 4.2.13 on 2024-05-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_collegestats_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestats',
            name='gpa',
            field=models.FloatField(),
        ),
    ]
