# Generated by Django 4.2.13 on 2024-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_collegestats_act_alter_collegestats_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestats',
            name='income',
            field=models.FloatField(),
        ),
    ]
