# Generated by Django 4.2.13 on 2024-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_collegestats_user_alter_collegestats_act_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestats',
            name='income',
            field=models.CharField(max_length=1000),
        ),
    ]
